# Generated by Django 3.1.6 on 2021-02-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('phone', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 2, 6, 7, 54, 53, 55484))),
            ],
        ),
    ]
